### ISSUE TITLE
Work in Rust 1.0

### ISSUE THREAD

**Issue by bluss** [reem/rust-debug-unreachable#1]
What do you think about providing unreachable in the crate, until it the intrinsic has been made stable?

The following compiles to the same as using the unreachable intrinsic. I'm not an LLVM wizard so I can't 100% guarantee it's valid, but I think it is.

``` rust
enum Void { }

unsafe fn unreachable() -> ! {
    let x: &Void = mem::transmute(&());
    match *x {
    }
}
```

**Comment by reem** [comment]
I would be happy to include this if someone more steeped in LLVM magicks (@aatch?) can attest that it will work.

**Comment by Aatch** [comment]
So this works because we add an `unreachable` instruction after calls to diverging functions. This:

``` rust
unsafe fn unreachable() -> ! { loop {} }
```

should also do the trick.

**Comment by bluss** [comment]
I'd be worried about that one, what happens if it is inlined?

**Comment by Aatch** [comment]
@bluss I'm pretty sure that the unreachable instruction would remain. We output the instruction after **calls** to divergent functions. So something like:

```
call @unreachable()
unreachable
```

I'd have to double-check, but I don't think LLVM will remove the `unreachable` during optimisation. Control reaching an unreachable instruction is considered undefined behaviour, so it might remove it when it can see it's truly unreachable (or more accurately, it's in an unreachable block), but if it can prove control reaches the instruction, it will probably replace the entire block it's in with a trap.

On top of that, "unreachable" code should be exactly that, unreachable. So it's not as if the unreachable instruction being removed will cause extra errors, just poorer codegen at worse.

**Comment by bluss** [comment]
Codegen is the reason for the optimization though.

I've tested both like this [(playpen link)](https://play.rust-lang.org/?gist=9bf18e8e32d7e3c59d08&version=nightly) and the void version has better codegen. It does unfortunately compile the loop into a loop.

``` rust
#![crate_type="lib"]

#[inline(always)]
unsafe fn unreachable_loop() -> ! { loop {} }


use std::mem;
enum Void { }

#[inline(always)]
unsafe fn unreachable_void() -> ! {
    let v: &Void = mem::transmute(&());
    match *v {
    }
}

pub fn unwrap_a(foo: Option<i32>) -> i32 {
    match foo {
        Some(x) => x,
        None => unsafe { unreachable_loop() },
    }
}

pub fn unwrap_b(foo: Option<i32>) -> i32 {
    match foo {
        Some(x) => x,
        None => unsafe { unreachable_void() },
    }
}
```

**Comment by reem** [comment]
Done!

I accomplished this by adding a safe unreachable to the `void` crate, which now runs on stable, depending on that in a new `unreachable` crate providing an unsafe `unreachable` with the same interface as the intrinsic, then using that crate here.

**Comment by reem** [comment]
I used the empty match approach rather than the loop approach, fwiw.

**Comment by bluss** [comment]
thank you!
